name: Insert Data

on:
  issues:
    types: [opened]

  workflow_dispatch:
  
concurrency:
  group: ${{ github.workflow }}-${{ github.run_id }}

  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x
          
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
        
      - if: startsWith(github.event.issue.title, 'WRITE_TREND') == true
        name: Write trend to database
        run: deno run -q --allow-read --allow-write --allow-run --allow-net --allow-env --unstable cli/write_trends.ts '${{ github.event.issue.body }}'

      - if: startsWith(github.event.issue.title, 'WRITE_PRODUCT') == true
        name: Write Product to database
        run: |
           echo GH_TOKEN=$GH_TOKEN >> .env
           export $(cat .env | xargs)
           deno run -q --allow-read --allow-write --allow-run --allow-net --allow-env --unstable cli/write_products_gist.ts '${{github.event.issue.body}}'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        
      - name: Commit & Push changes
        uses: Wandalen/wretry.action@v1.0.11
        with:
          action: actions-js/push@master
          with: |
            github_token: ${{ secrets.GH_TOKEN }}
            branch: main
            force: true
          attempt_limit: 5
          attempt_delay: 2000
          
      - if: startsWith(github.event.issue.title, 'WRITE_TREND') == true
        name: Close Issue
        uses: peter-evans/close-issue@v2
        with:
          comment: |
            Trend data successfully inserted. Closing issue...

      - if: startsWith(github.event.issue.title, 'WRITE_TREND') == true
        name: Forward trend to product
        run: |
           echo GH_TOKEN=$GH_TOKEN >> .env
           export $(cat .env | xargs)
           deno run -q --allow-read --allow-write --allow-run --allow-net --allow-env --unstable cli/forward_trends.ts
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        
      - if: startsWith(github.event.issue.title, 'WRITE_PRODUCT') == true
        name: Close Issue
        uses: peter-evans/close-issue@v2
        with:
          comment: |
            Product data successfully inserted. Closing issue...
