name: Insert Data

on:
  issues:
    types: [opened]

  workflow_dispatch:
  
concurrency: ci-${{ github.ref }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x
          
      - name: Check out repo
        uses: actions/checkout@v2
        
      - if: startsWith(github.event.issue.title, 'WRITE_TREND') == true
        name: Write trend to database
        run: deno run -q --allow-read --allow-write --allow-run --allow-net --allow-env --unstable cli/write_trends.ts '${{ github.event.issue.body }}'

      - if: startsWith(github.event.issue.title, 'WRITE_PRODUCT') == true
        name: Write trend to database
        run: deno run -q --allow-read --allow-write --allow-run --allow-net --allow-env --unstable cli/write_products.ts '${{ github.event.issue.body }}'
        
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          branch: main
          force: true
          
      - if: startsWith(github.event.issue.title, 'WRITE_TREND') == true
        name: Close Issue
        uses: peter-evans/close-issue@v2
        with:
          comment: |
            Trend data successfully inserted. Closing issue...
        

      - if: startsWith(github.event.issue.title, 'WRITE_PRODUCT') == true
        name: Close Issue
        uses: peter-evans/close-issue@v2
        with:
          comment: |
            Product data successfully inserted. Closing issue...
